Repository woven-planet/go-zserio, pull requests merged in 2022-02, with the labels that each got.

#59 Document pre-v1 versioning scheme
  README.md
Labels: documentation

#50 Fix Ambiguous Selector Values in Choices
  internal/ast/choice.go
  internal/generator/templates/choice.go.tmpl
  internal/model/transform.go
  internal/visitor/visitor.go
  test/python/BUILD.bazel
  test/python/write_test_data.py
  testdata/reference_modules/core/types.zs
  testdata/reference_modules/testobject1/testobject.zs
Labels: bug

#58 Add automated release configuration
  .github/release.yml
Labels: ignore for release

#61 Add Marshal and Unmarshal functions to facilitate converting to bytes
  BUILD.bazel
  doc.go
  example/main.go
  marshal.go
  test/BUILD.bazel
  test/integration_test.go
  ztype/array_encode_test.go
Labels: enhancement

#60 Add a bazel rule for python library generation and reorganize test code
  BUILD.bazel
  WORKSPACE
  deps.bzl
  go.mod
  go.sum
  test/BUILD.bazel
  test/features/compare_with_zserio_reference.feature
  test/go/BUILD.bazel
  test/integration_test.go
  test/python/BUILD.bazel
  test/reference/BUILD.bazel
  test/reference/data.py
  test/reference/reference_test.go
  test/rules/BUILD.bazel
  test/rules/requirements.txt
  test/rules/rules.bzl
  test/rules/write_data.py
  testdata/BUILD.bazel
  testdata/reference_modules/BUILD.bazel
Labels: ignore for release

#64 Use our own reader and writer in the marshaling interfaces
  BUILD.bazel
  example/go.mod
  iface.go
  internal/generator/templates/bitmask.go.tmpl
  internal/generator/templates/choice.go.tmpl
  internal/generator/templates/decode.go.tmpl
  internal/generator/templates/encode.go.tmpl
  internal/generator/templates/enum.go.tmpl
  internal/generator/templates/packing_context_decode.go.tmpl
  internal/generator/templates/packing_context_encode.go.tmpl
  internal/generator/templates/struct.go.tmpl
  internal/generator/templates/union.go.tmpl
  marshal.go
  packing_context_node.go
  reader.go
  reader_test.go
  rules.bzl
  test/reference/BUILD.bazel
  writer.go
  writer_test.go
  ztype/BUILD.bazel
  ztype/array.go
  ztype/array_decode.go
  ztype/array_decode_test.go
  ztype/array_encode.go
  ztype/array_traits.go
  ztype/bit_alignment.go
  ztype/bits_decode.go
  ztype/bits_decode_test.go
  ztype/bits_encode.go
  ztype/bits_encode_test.go
  ztype/bool_decode.go
  ztype/bool_decode_test.go
  ztype/bool_encode.go
  ztype/bool_encode_test.go
  ztype/delta_context.go
  ztype/extern_decode.go
  ztype/extern_encode.go
  ztype/float_decode.go
  ztype/float_decode_test.go
  ztype/float_encode.go
  ztype/float_encode_test.go
  ztype/packed_array_traits.go
  ztype/string_decode.go
  ztype/string_decode_test.go
  ztype/string_encode.go
  ztype/string_encode_test.go
  ztype/varint_decode.go
  ztype/varint_decode_test.go
  ztype/varint_encode.go
  ztype/varint_encode_test.go
  ztype/varuint_decode.go
  ztype/varuint_decode_test.go
  ztype/varuint_encode.go
  ztype/varuint_encode_test.go
Labels: breaking change

#63 Resolve FIXMEs in Reference Tests
  test/reference/reference_test.go
Labels: ignore for release

#44 add the first reference data (de)serialization benchmarks
  test/reference/reference_test.go
Labels: ignore for release

#65 Use interfaces instead of structs in Marshaling interfaces
  BUILD.bazel
  iface.go
  internal/generator/templates/bitmask.go.tmpl
  internal/generator/templates/choice.go.tmpl
  internal/generator/templates/enum.go.tmpl
  internal/generator/templates/struct.go.tmpl
  internal/generator/templates/union.go.tmpl
  marshal.go
  packing_context_node.go
  zstream/BUILD.bazel
  zstream/reader.go
  zstream/reader_test.go
  zstream/writer.go
  zstream/writer_test.go
  ztype/BUILD.bazel
  ztype/array_decode.go
  ztype/array_decode_test.go
  ztype/array_encode.go
  ztype/array_traits.go
  ztype/bits_decode.go
  ztype/bits_decode_test.go
  ztype/bits_encode.go
  ztype/bits_encode_test.go
  ztype/bool_decode.go
  ztype/bool_decode_test.go
  ztype/bool_encode.go
  ztype/bool_encode_test.go
  ztype/delta_context.go
  ztype/extern_decode.go
  ztype/extern_encode.go
  ztype/float_decode.go
  ztype/float_decode_test.go
  ztype/float_encode.go
  ztype/float_encode_test.go
  ztype/packed_array_traits.go
  ztype/string_decode.go
  ztype/string_decode_test.go
  ztype/string_encode.go
  ztype/string_encode_test.go
  ztype/varint_decode.go
  ztype/varint_decode_test.go
  ztype/varint_encode.go
  ztype/varint_encode_test.go
  ztype/varuint_decode.go
  ztype/varuint_decode_test.go
  ztype/varuint_encode.go
  ztype/varuint_encode_test.go
Labels: breaking change
